[package]
name = "fracture-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.26.0"
crossterm = "0.27.0"
color-eyre = "0.6.2"
polars = { version = "0.38.0", features = ["parquet", "lazy"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
