[package]
name = "bios-menu"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26.0"
crossterm = "0.27.0"
clap = { version = "4.4", features = ["derive"] }
walkdir = "2.4.0"
glob = "0.3.1"
shellexpand = "3.1.0"

[profile.release]
panic = 'abort'
